
class MovieFinder:
    def __init__(self):
        self.movies_bollywood = {
            'Dunki': ['Shah Rukh Khan', 'Katrina Kaif', 'Taapsee Pannu', 'Boman Irani'],
            'Fighter': ['Hrithik Roshan', 'Deepika Padukone', 'Anil Kapoor', 'Kriti Sanon'],
            'Rocky Aur Rani Ki Prem Kahani': ['Ranveer Singh', 'Alia Bhatt', 'Dharmendra', 'Shabana Azmi', 'Jaya Bachchan'],
            'Tejas': ['Kangana Ranaut', 'Anupam Kher', 'R. Sarathkumar'],
            'Kisi Ka Bhai Kisi Ki Jaan': ['Salman Khan', 'Pooja Hegde', 'Venkatesh Daggubati', 'Shehnaaz Gill'],
            'Bade Miyan Chote Miyan': ['Amitabh Bachchan', 'Tiger Shroff', 'Akshay Kumar', 'Alaya F'],
            'Ganapath': ['Tiger Shroff', 'Kriti Sanon', 'Amitabh Bachchan', 'Naseeruddin Shah'],
            'Tiger 3': ['Salman Khan', 'Katrina Kaif', 'Emraan Hashmi'],
            'Jee Le Zaraa': ['Priyanka Chopra', 'Alia Bhatt', 'Katrina Kaif', 'Farhan Akhtar (director)'],
            'Brahmāstra 2: The Age of God': ['Ranbir Kapoor', 'Alia Bhatt', 'Amitabh Bachchan', 'Mouni Roy'],
            'Kalki 2898 AD': ['Amitabh Bachchan', 'Prabhas', 'Deepika Padukone', 'Disha Patani'],
            'Satyaprem Ki Katha': ['Kartik Aaryan', 'Kiara Advani', 'Gajraj Rao'],
            'Hera Pheri 3': ['Akshay Kumar', 'Sunil Shetty', 'Paresh Rawal'],
            'Race 4': ['Salman Khan', 'Jacqueline Fernandez', 'Shraddha Kapoor'],
            'Thank God 2': ['Ajay Devgn', 'Sidharth Malhotra', 'Rakul Preet Singh'],
            'Lootcase 2': ['Kunal Khemu', 'Rasika Dugal', 'Vijay Raaz'],
            'Gully Boy 2': ['Ranveer Singh', 'Alia Bhatt', 'Siddhant Chaturvedi'],
            'Sarkar 4': ['Amitabh Bachchan', 'Abhishek Bachchan'],
            'Chupke Chupke 2': ['Amitabh Bachchan', 'Rajesh Sharma', 'Radhika Apte'],
            'Madhuri Dixit’s Untitled Film': ['Madhuri Dixit', 'Kartik Aaryan'],
            'Patiala House 2': ['Akshay Kumar', 'Anushka Sharma', 'Rishi Kapoor'],
            'Murder 5': ['Emraan Hashmi', 'Richa Chadha'],
            'Zindagi Na Milegi Dobara 2': ['Hrithik Roshan', 'Farhan Akhtar', 'Katrina Kaif', 'Kalki Koechlin'],
            # 2023 Movies
            'Pathaan': ['Shah Rukh Khan', 'Deepika Padukone', 'John Abraham', 'Dimple Kapadia'],
            'Jawan': ['Shah Rukh Khan', 'Nayanthara', 'Vijay Sethupathi', 'Sanya Malhotra', 'Priyamani'],
            'Tu Jhoothi Main Makkar': ['Ranbir Kapoor', 'Shraddha Kapoor', 'Anubhav Singh Bassi', 'Dimple Kapadia'],
            'Rocky Aur Rani Ki Prem Kahani': ['Ranveer Singh', 'Alia Bhatt', 'Dharmendra', 'Shabana Azmi', 'Jaya Bachchan'],
            'Brahmāstra: Part One – Shiva': ['Ranbir Kapoor', 'Alia Bhatt', 'Amitabh Bachchan', 'Nagarjuna', 'Mouni Roy'],
            'Govinda Naam Mera': ['Vicky Kaushal', 'Kiara Advani', 'Bhumi Pednekar', 'Kayoze Irani'],
            'Mili': ['Janvhi Kapoor', 'Manoj Pahwa', 'Sunny Kaushal', 'Vikram Kochhar'],
            'Shehzada': ['Kartik Aaryan', 'Kriti Sanon', 'Paresh Rawal', 'Ronit Roy'],
            'Samrat Prithviraj': ['Akshay Kumar', 'Manushi Chhillar', 'Sanjay Dutt', 'Sonu Sood'],
            'Luv Ranjan’s Untitled Film': ['Ranbir Kapoor', 'Shraddha Kapoor', 'Boney Kapoor', 'Dimple Kapadia'],
            'Satyaprem Ki Katha': ['Kartik Aaryan', 'Kiara Advani', 'Gajraj Rao', 'Rajpal Yadav'],
            'Rannbhoomi': ['Vicky Kaushal', 'Kiara Advani', 'Rakul Preet Singh', 'Ronit Roy'],
            'Chup': ['Sunny Deol', 'Dulquer Salmaan', 'Shreya Dhanwanthary', 'Pooja Bhatt'],
            'Liger': ['Vijay Deverakonda', 'Ananya Panday', 'Mike Tyson', 'Ramya Krishnan'],
            'Cirkus': ['Ranveer Singh', 'Pooja Hegde', 'Jacqueline Fernandez', 'Varun Sharma'],
            'Maidaan': ['Ajay Devgn', 'Priyamani', 'Gajraj Rao', 'Raghubir Yadav'],
            'Bhediya': ['Varun Dhawan', 'Kriti Sanon', 'Deepak Dobriyal', 'Abhishek Banerjee'],
            'Drishyam 2': ['Ajay Devgn', 'Tabu', 'Rajat Kapoor', 'Akshaye Khanna'],
            'Bawaal': ['Varun Dhawan', 'Janvhi Kapoor', 'Saurabh Shukla'],
            'Ponniyin Selvan 1 (Hindi Dubbed)': ['Vikram', 'Aishwarya Rai Bachchan', 'Karthi', 'Jayam Ravi'],
            'Jersey': ['Shahid Kapoor', 'Mrunal Thakur', 'Pankaj Kapoor'],
            'Hera Pheri 3': ['Akshay Kumar', 'Sunil Shetty', 'Paresh Rawal', 'Kartik Aaryan'],
            'Bhaijaan': ['Salman Khan', 'Pooja Hegde', 'Venkatesh Daggubati', 'Shehnaaz Gill'],
            'Vikram Vedha (Remake)': ['Hrithik Roshan', 'Saif Ali Khan', 'Radhika Apte'],
            'Thank God': ['Ajay Devgn', 'Sidharth Malhotra', 'Rakul Preet Singh'],
            'Kisi Ka Bhai Kisi Ki Jaan': ['Salman Khan', 'Pooja Hegde', 'Venkatesh Daggubati', 'Shehnaaz Gill'],
            'Fukrey 3': ['Pulkit Samrat', 'Varun Sharma', 'Manjot Singh', 'Richa Chadha'],
            'Chhori 2': ['Nushrat Bharucha', 'Mita Vashisht', 'Rajesh Sharma'],
            'Murder Mubarak': ['Kartik Aaryan', 'Kiara Advani', 'Ananya Panday', 'Rajpal Yadav'],
            'Gadar 2': ['Sunny Deol', 'Amisha Patel', 'Zarina Wahab', 'Utkarsh Sharma'],
            'Bholaa': ['Ajay Devgn', 'Tabu', 'Raai Laxmi', 'Deepak Dobriyal'],
            'Aashiqui 3': ['Aditya Roy Kapur', 'Ananya Panday', 'Shaarib Hashmi'],
            'Dhamaka': ['Kartik Aaryan', 'Mrunal Thakur', 'Amruta Subhash', 'Vikrant Massey'],
            'Laal Singh Chaddha (Re-release)': ['Aamir Khan', 'Kareena Kapoor Khan', 'Naga Chaitanya'],
            'Koi Jaane Na': ['Kunal Kapoor', 'Amyra Dastur', 'Denzil Smith'],
            'Mili': ['Janhvi Kapoor', 'Manoj Pahwa', 'Sunny Kaushal', 'Vikram Kochhar'],
            'Panchayat 2 (Film)': ['Jitendra Kumar', 'Raghubir Yadav', 'Neena Gupta'],
            'Cuttputlli': ['Akshay Kumar', 'Sargun Mehta', 'Chandrachur Singh', 'Rajesh Sharma'],
            'Hindutva': ['Sumit Tiwari', 'Sreejita De', 'Rajesh Sharma'],
            'Uunchai': ['Amitabh Bachchan', 'Anupam Kher', 'Boman Irani', 'Parineeti Chopra'],
            'Rakhi Sawant’s Untitled Film': ['Rakhi Sawant', 'Munni Badnam Hui', 'Sambhavna Seth'],
            'Mere Haath Mein': ['Raveena Tondon', 'Kunal Khemu', 'Rajkummar Rao'],
            'Yash Raj Films Untitled Project': ['Shah Rukh Khan', 'Katrina Kaif', 'John Abraham'],
            'Ponniyin Selvan 2 (Hindi Dubbed)': ['Vikram', 'Aishwarya Rai Bachchan', 'Karthi', 'Jayam Ravi'],
            'Dream Girl 2': ['Ayushmann Khurrana', 'Ananya Panday', 'Paresh Rawal', 'Rajpal Yadav', 'Manoj Joshi'],
            'Dream Girl': ['Ayushmann Khurrana', 'Nushrat Bharucha', 'Annu Kapoor', 'Vijay Raaz', 'Manoj Joshi'],
            # 2022 Movies
            'Brahmāstra: Part One – Shiva': ['Ranbir Kapoor', 'Alia Bhatt', 'Amitabh Bachchan', 'Nagarjuna', 'Mouni Roy'],
            'The Kashmir Files': ['Darshan Kumar', 'Anupam Kher', 'Mithun Chakraborty', 'Pallavi Joshi'],
            'Gangubai Kathiawadi': ['Alia Bhatt', 'Ajay Devgn', 'Shantanu Maheshwari', 'Vijay Raaz'],
            'Drishyam 2': ['Ajay Devgn', 'Tabu', 'Rajat Kapoor', 'Akshaye Khanna'],
            'Badhaai Do': ['Rajkummar Rao', 'Bhumi Pednekar', 'Seema Pahwa', 'Shivankit Singh Parihar'],
            'Jersey': ['Shahid Kapoor', 'Mrunal Thakur', 'Pankaj Kapoor', 'Rohit Raj'],
            'RRR (Hindi Dubbed)': ['Ram Charan', 'N. T. Rama Rao Jr.', 'Alia Bhatt', 'Ajay Devgn'],
            'Bhool Bhulaiyaa 2': ['Kartik Aaryan', 'Kiara Advani', 'Tabu', 'Rajpal Yadav'],
            'Laal Singh Chaddha': ['Aamir Khan', 'Kareena Kapoor Khan', 'Naga Chaitanya', 'Mona Singh'],
            'Kantara (Hindi Dubbed)': ['Rishab Shetty', 'Saptami Gowda', 'Kishore'],
            'Rocketry: The Nambi Effect': ['R. Madhavan', 'Simran', 'Rajit Kapur', 'Madhavan'],
            'Atrangi Re': ['Akshay Kumar', 'Dhanush', 'Sara Ali Khan', 'Nia Sharma'],
            'Cirkus': ['Ranveer Singh', 'Pooja Hegde', 'Jacqueline Fernandez', 'Varun Sharma'],
            'Maidaan': ['Ajay Devgn', 'Priyamani', 'Gajraj Rao', 'Raghubir Yadav'],
            'Lal Kaptaan': ['Saif Ali Khan', 'Sonakshi Sinha', 'Zoya Hussain', 'Manav Vij'],
            'Antim: The Final Truth': ['Salman Khan', 'Aayush Sharma', 'Mahima Makwana'],
            'Shamshera': ['Ranbir Kapoor', 'Vaani Kapoor', 'Sanjay Dutt', 'Ronit Roy'],
            'Jayeshbhai Jordaar': ['Ranveer Singh', 'Shalini Pandey', 'Boman Irani', 'Ratna Pathak Shah'],
            'Haseen Dillruba': ['Taapsee Pannu', 'Vikrant Massey', 'Harshvardhan Rane', 'Aditya Srivastava'],
            'Runway 34': ['Ajay Devgn', 'Amitabh Bachchan', 'Rakul Preet Singh', 'Angira Dhar'],
            'Rashtra Kavach Om': ['Aditya Roy Kapur', 'Sanjana Sanghi', 'Jackie Shroff'],
            'Nikamma': ['Shilpa Shetty', 'Abhimanyu Dassani', 'Shireen Mirza', 'Samir Soni'],
            'Dhaakad': ['Kangana Ranaut', 'Arjun Rampal', 'Divya Dutta', 'Sohaila Kapoor'],
            'Jugjugg Jeeyo': ['Varun Dhawan', 'Kiara Advani', 'Anil Kapoor', 'Neetu Kapoor'],
            'Vikram': ['Kamal Haasan', 'Vijay Sethupathi', 'Fahadh Faasil', 'Suriya'],
            'Bhool Bhulaiyaa 2': ['Kartik Aaryan', 'Kiara Advani', 'Tabu', 'Rajpal Yadav'],
            'Chup: Revenge of the Artist': ['Sunny Deol', 'Dulquer Salmaan', 'Shreya Dhanwanthary', 'Pooja Bhatt'],
            'Gehraiyaan': ['Deepika Padukone', 'Siddhant Chaturvedi', 'Ananya Panday', 'Dhairya Karwa'],
            'Code Name: Tiranga': ['Parineeti Chopra', 'Harrdy Sandhu', 'Sharib Hashmi'],
            'Jersey': ['Shahid Kapoor', 'Mrunal Thakur', 'Pankaj Kapoor'],
            'Bachchhan Paandey': ['Akshay Kumar', 'Kriti Sanon', 'Jacqueline Fernandez', 'Arshad Warsi'],
            'Looop Lapeta': ['Taapsee Pannu', 'Tahir Raj Bhasin', 'Shiv Panditt'],
            'Satyam Shivam Sundaram': ['Rani Mukerji', 'Sushant Singh Rajput'],
            'Thank God': ['Ajay Devgn', 'Sidharth Malhotra', 'Rakul Preet Singh'],
            'Ram Setu': ['Akshay Kumar', 'Jacqueline Fernandez', 'Nushrratt Bharuccha', 'Satyadev Kancharana'],
            'Maja Ma': ['Madhuri Dixit', 'Gajraj Rao', 'Ritwik Bhowmik', 'Srishti Shrivastava'],
            'Doctor G': ['Ayushmann Khurrana', 'Rakul Preet Singh', 'Shefali Shah'],
            'Bhediya': ['Varun Dhawan', 'Kriti Sanon', 'Deepak Dobriyal', 'Abhishek Banerjee'],
            'F3: Fun and Frustration': ['Venkatesh Daggubati', 'Varun Tej', 'Tamannaah Bhatia', 'Mehreen Pirzada'],
            'Kartik Aaryan’s Untitled Film': ['Kartik Aaryan', 'Kiara Advani', 'Rakul Preet Singh'],

            # 2021 Movies
            'Sooryavanshi': ['Akshay Kumar', 'Katrina Kaif', 'Ajay Devgn', 'Ranveer Singh'],
            'Kabir Singh': ['Shahid Kapoor', 'Kiara Advani', 'Suresh Oberoi', 'Aditi Rao Hydari'],
            'Sandeep Aur Pinky Faraar': ['Arjun Kapoor', 'Parineeti Chopra', 'Raghubir Yadav', 'Nina Kulkarni'],
            'Bell Bottom': ['Akshay Kumar', 'Vaani Kapoor', 'Lara Dutta', 'Huma Qureshi'],
            'Shershaah': ['Sidharth Malhotra', 'Kiara Advani', 'Shiv Panditt', 'Jaaved Jaffrey'],
            'Chehre': ['Amitabh Bachchan', 'Emraan Hashmi', 'Annu Kapoor', 'Rhea Chakraborty'],
            'Thalaivii': ['Kangana Ranaut', 'Arvind Swami', 'Raj Arjun', 'Bhagyashree'],
            'Atrangi Re': ['Akshay Kumar', 'Dhanush', 'Sara Ali Khan', 'Nia Sharma'],
            'Mumbai Mafia: Police vs The Underworld': ['Javed Jaffrey', 'Vijay Maurya'],
            'F9: The Fast Saga (Hindi Dubbed)': ['Vin Diesel', 'John Cena', 'Michelle Rodriguez', 'Tyrese Gibson'],
            'Radhe': ['Salman Khan', 'Disha Patani', 'Randeep Hooda', 'Jackie Shroff'],
            'Raat Akeli Hai': ['Nawazuddin Siddiqui', 'Radhika Apte', 'Shweta Tripathi', 'Kali Prasad Mukherjee'],
            'The White Tiger': ['Adarsh Gourav', 'Priyanka Chopra', 'Rajkummar Rao', 'Mahesh Manjrekar'],
            'Ajeeb Daastaans': ['Naseeruddin Shah', 'Fatima Sana Shaikh', 'Arjun Kapoor', 'Manav Kaul'],
            'Roohi': ['Rajkummar Rao', 'Janvhi Kapoor', 'Varun Sharma', 'Seema Pahwa'],
            'Toofan': ['Farhan Akhtar', 'Paresh Rawal', 'Mrunal Thakur', 'Supriya Pathak'],
            'Radhe Shyam': ['Prabhas', 'Pooja Hegde', 'Sachin Khedekar', 'Bhagyashree'],
            'Bunty Aur Babli 2': ['Saif Ali Khan', 'Rani Mukerji', 'Siddhant Chaturvedi', 'Sharvari Wagh'],
            'Ludo': ['Pankaj Tripathi', 'Abhishek Bachchan', 'Rajkummar Rao', 'Sanya Malhotra'],
            'Mumbai Diaries 26/11': ['Mohit Raina', 'Kriti Kharbanda', 'Sharib Hashmi', 'Satyajeet Dubey'],
            'Gunjan Saxena: The Kargil Girl': ['Janvhi Kapoor', 'Pankaj Tripathi', 'Angad Bedi', 'Vineet Kumar'],
            'The Big Bull': ['Abhishek Bachchan', 'Nikita Dutta', 'Sohum Shah', 'Sumit Vyas'],
            'Pagglait': ['Sanya Malhotra', 'Shruti Sharma', 'Ashutosh Rana', 'Sayani Gupta'],
            'Chandigarh Kare Aashiqui': ['Ayushmann Khurrana', 'Vaani Kapoor', 'Abhishek Bajaj', 'Gourav Sharma'],
            'Jungle Cry': ['Abhay Deol', 'Krutika Deo', 'Emily Shah', 'Annanya Ghosh'],
            'Satyam Shivam Sundaram': ['Rani Mukerji', 'Sushant Singh Rajput'],
            'Nail Polish': ['Arjun Rampal', 'Manav Kaul', 'Raghubir Yadav', 'Rajeev Khandelwal'],
            'Antim: The Final Truth': ['Salman Khan', 'Aayush Sharma', 'Mahima Makwana', 'Niketan Dheer'],
            'Vakeel Saab (Hindi Dubbed)': ['Pawan Kalyan', 'Shruti Haasan', 'Ananya Nagalla', 'Prakash Raj'],
            'Dhamaka': ['Kartik Aaryan', 'Mrunal Thakur', 'Amruta Subhash', 'Vikrant Massey'],
            'Pati Patni Aur Woh (Remake)': ['Kartik Aaryan', 'Ananya Panday', 'Bhumi Pednekar', 'Madhuri Dixit'],
            'Bhoot Police': ['Saif Ali Khan', 'Arjun Kapoor', 'Jacqueline Fernandez', 'Yami Gautam'],
            'Mimi': ['Kriti Sanon', 'Pankaj Tripathi', 'Sai Tamhankar', 'Supriya Pathak'],
            'Chhorii': ['Nushrratt Bharuccha', 'Mita Vashisht', 'Rajesh Sharma'],
            'Rashmi Rocket': ['Taapsee Pannu', 'Abhishek Banerjee', 'Shweta Tripathi'],
            'Shiddat': ['Sunny Kaushal', 'Radhika Madan', 'Mohit Raina', 'Diana Penty'],
            'Aarya 2': ['Sushmita Sen', 'Chandrachur Singh', 'Vikas Kumar', 'Maya Sarao'],
            'The Girl on the Train (Hindi Remake)': ['Parineeti Chopra', 'Avinash Tiwary', 'Aditi Rao Hydari', 'Kirti Kulhari'],
            'Raat Baaki': ['Radhika Apte', 'Nawazuddin Siddiqui', 'Madhuri Dixit'],

            # 2020 Movies
            'Tanhaji: The Unsung Warrior': ['Ajay Devgn', 'Saif Ali Khan', 'Kajol', 'Sharad Kelkar'],
            'Chhapaak': ['Deepika Padukone', 'Vikrant Massey', 'Madhurjeet Sarghi'],
            'Shubh Mangal Zyada Saavdhan': ['Ayushmann Khurrana', 'Jitendra Kumar', 'Gajraj Rao', 'Neena Gupta'],
            'Bhoot: Part One – The Haunted Ship': ['Vicky Kaushal', 'Bhumi Pednekar', 'Ashutosh Rana'],
            'Baaghi 3': ['Tiger Shroff', 'Shraddha Kapoor', 'Riteish Deshmukh', 'Ankita Lokhande'],
            'Angrezi Medium': ['Irrfan Khan', 'Radhika Madan', 'Kareena Kapoor Khan', 'Deepak Dobriyal'],
            'Street Dancer 3D': ['Varun Dhawan', 'Shraddha Kapoor', 'Prabhu Deva', 'Nora Fatehi'],
            'Panga': ['Kangana Ranaut', 'Jassie Gill', 'Richa Chadha', 'Neena Gupta'],
            'Coolie No. 1': ['Varun Dhawan', 'Sara Ali Khan', 'Paresh Rawal', 'Rajpal Yadav'],
            'Laxmii': ['Akshay Kumar', 'Kiara Advani', 'Sharad Kelkar', 'Ayesha Raza'],
            'Khaali Peeli': ['Ishaan Khatter', 'Ananya Panday', 'Jaideep Ahlawat', 'Shalini Pandey'],
            'Sadak 2': ['Alia Bhatt', 'Aditya Roy Kapur', 'Pooja Bhatt', 'Sanjay Dutt'],
            'The Big Bull': ['Abhishek Bachchan', 'Nikita Dutta', 'Sohum Shah', 'Sumit Vyas'],
            'Gunjan Saxena: The Kargil Girl': ['Janvhi Kapoor', 'Pankaj Tripathi', 'Angad Bedi', 'Vineet Kumar'],
            'Ludo': ['Pankaj Tripathi', 'Abhishek Bachchan', 'Rajkummar Rao', 'Sanya Malhotra'],
            'Kaamyaab': ['Sanjay Mishra', 'Deepak Dobriyal', 'Sarika Singh', 'Ila Arun'],
            'Raat Akeli Hai': ['Nawazuddin Siddiqui', 'Radhika Apte', 'Shweta Tripathi', 'Kali Prasad Mukherjee'],
            'Gulabo Sitabo': ['Amitabh Bachchan', 'Ayushmann Khurrana', 'Farrukh Jaffar', 'Suhail Nayyar'],
            'Shakuntala Devi': ['Vidya Balan', 'Sanya Malhotra', 'Jisshu Sengupta', 'Amit Sadh'],
            'Dil Bechara': ['Sushant Singh Rajput', 'Sanjana Sanghi', 'Sahil Vaid', 'Swastika Mukherjee'],
            'Bhaag Beanie Bhaag': ['Swara Bhasker', 'Shikha Talsania', 'Ranjit Kaur', 'Meherzan Mazda'],
            'Choked': ['Saiyami Kher', 'Roshan Mathew', 'Amruta Subhash', 'Rajshri Deshpande'],
            'Ajeeb Daastaans': ['Naseeruddin Shah', 'Fatima Sana Shaikh', 'Arjun Kapoor', 'Manav Kaul'],
            'Haathi Mere Saathi (Remake)': ['Rani Mukerji', 'Shivendra Bansal', 'Rajeev Khandelwal'],
            'Unpaused': ['Richa Chadha', 'Ratna Pathak Shah', 'Sumeet Vyas', 'Shreya Dhanwanthary'],
            'Rashmi Rocket': ['Taapsee Pannu', 'Abhishek Banerjee', 'Shweta Tripathi'],
            'Mumbai Mafia: Police vs The Underworld': ['Javed Jaffrey', 'Vijay Maurya'],
            'Lootcase': ['Kunal Khemu', 'Rasika Dugal', 'Vijay Raaz', 'Gajraj Rao'],
            'Chhoti Si Baat': ['Rajkummar Rao', 'Kriti Sanon', 'Dinesh Rawat', 'Yashpal Sharma'],
            'Drishyam 2 (Hindi Dubbed)': ['Ajay Devgn', 'Tabu', 'Rajat Kapoor', 'Akshaye Khanna'],
            'Sushant Singh Rajput’s Untitled Film': ['Sushant Singh Rajput', 'Ayesha Raza Mishra', 'Shraddha Kapoor'],

            # 2019 Movies
            'War': ['Hrithik Roshan', 'Tiger Shroff', 'Vaani Kapoor', 'Anupriya Goenka'],
            'Kabir Singh': ['Shahid Kapoor', 'Kiara Advani', 'Suresh Oberoi', 'Aditi Rao Hydari'],
            'Uri: The Surgical Strike': ['Vicky Kaushal', 'Paresh Rawal', 'Yami Gautam', 'Mohit Raina'],
            'Gully Boy': ['Ranveer Singh', 'Alia Bhatt', 'Siddhant Chaturvedi', 'Vijay Varma'],
            'Bharat': ['Salman Khan', 'Katrina Kaif', 'Disha Patani', 'Jackie Shroff'],
            'Total Dhamaal': ['Ajay Devgn', 'Anil Kapoor', 'Madhuri Dixit', 'Riteish Deshmukh'],
            'Good Newwz': ['Akshay Kumar', 'Kareena Kapoor Khan', 'Diljit Dosanjh', 'Kiara Advani'],
            'Street Dancer 3D': ['Varun Dhawan', 'Shraddha Kapoor', 'Prabhu Deva', 'Nora Fatehi'],
            'Chhichhore': ['Sushant Singh Rajput', 'Shraddha Kapoor', 'Varun Sharma', 'Naveen Polishetty'],
            'Mission Mangal': ['Akshay Kumar', 'Vidya Balan', 'Sonakshi Sinha', 'Taapsee Pannu'],
            'Super 30': ['Hrithik Roshan', 'Mrunal Thakur', 'Pankaj Tripathi', 'Nandish Sandhu'],
            'Saaho': ['Prabhas', 'Shraddha Kapoor', 'Neil Nitin Mukesh', 'Jackie Shroff'],
            'Housefull 4': ['Akshay Kumar', 'Kriti Sanon', 'Bobby Deol', 'Riteish Deshmukh'],
            'Kesari': ['Akshay Kumar', 'Parineeti Chopra', 'Vishal Malhotra', 'Ravi Kishan'],
            'Batla House': ['John Abraham', 'Mrunal Thakur', 'Ravi Kishan', 'Kumud Mishra'],
            'Pati Patni Aur Woh': ['Kartik Aaryan', 'Bhumi Pednekar', 'Ananya Panday', 'Rajpal Yadav'],
            'Kalank': ['Varun Dhawan', 'Alia Bhatt', 'Sanjay Dutt', 'Madhuri Dixit'],
            'Tumbbad': ['Sohum Shah', 'Jyoti Malshe', 'Vineet Sharma', 'Ronjini Chakraborty'],
            'Jabariya Jodi': ['Sidharth Malhotra', 'Parineeti Chopra', 'Javed Jaffrey', 'Akhilendra Mishra'],
            'Batla House': ['John Abraham', 'Mrunal Thakur', 'Ravi Kishan', 'Kumud Mishra'],
            'The Zoya Factor': ['Sonam Kapoor', 'Dulquer Salmaan', 'Angad Bedi', 'Manish Chaudhari'],
            'Marjaavaan': ['Sidharth Malhotra', 'Rakul Preet Singh', 'Tara Sutaria', 'Riteish Deshmukh'],
            'De De Pyaar De': ['Ajay Devgn', 'Rakul Preet Singh', 'Tabu', 'Javed Jaffrey'],
            'Junglee': ['Vidyut Jammwal', 'Pooja Sawant', 'Asha Bhat', 'Jameel Khoury'],
            'Warina Hussain’s Film': ['Warina Hussain', 'Aayush Sharma'],
            'Dream Girl': ['Ayushmann Khurrana', 'Nushrat Bharucha', 'Annu Kapoor', 'Manjot Singh'],
            'Madhuri Dixit’s Film': ['Madhuri Dixit', 'Sumeet Vyas'],
            'Jab Tak Hai Jaan 2': ['Shah Rukh Khan', 'Katrina Kaif'],
            'Arjun Patiala': ['Diljit Dosanjh', 'Kriti Sanon', 'Varun Sharma', 'Seema Pahwa'],
            'Sandeep Aur Pinky Faraar': ['Arjun Kapoor', 'Parineeti Chopra', 'Raghubir Yadav', 'Nina Kulkarni'],
            'Bala': ['Ayushmann Khurrana', 'Bhumi Pednekar', 'Yami Gautam', 'Seema Pahwa'],
            'Mardaani 2': ['Rani Mukerji', 'Vishal Jethwa', 'Shruti Bapna', 'Sanjay Tiwari'],
            'The Fakir of Venice': ['Farhan Akhtar', 'Anupam Kher', 'Kamlesh Gill', 'Rajit Kapur'],
            'Shubh Mangal Zyada Saavdhan': ['Ayushmann Khurrana', 'Jitendra Kumar', 'Gajraj Rao', 'Neena Gupta'],
            'Pagalpanti': ['John Abraham', 'Anil Kapoor', 'Kriti Kharbanda', 'Arshad Warsi'],
            'Panga': ['Kangana Ranaut', 'Jassie Gill', 'Richa Chadha', 'Neena Gupta'],
            'Chhapaak': ['Deepika Padukone', 'Vikrant Massey', 'Madhurjeet Sarghi'],
            'Gully Boy': ['Ranveer Singh', 'Alia Bhatt', 'Siddhant Chaturvedi', 'Vijay Varma'],

            # 2018 Movies
            'Sanju': ['Ranbir Kapoor', 'Paresh Rawal', 'Vicky Kaushal', 'Anushka Sharma'],
            '2.0': ['Rajinikanth', 'Akshay Kumar', 'Amy Jackson', 'Sudhanshu Pandey'],
            'Dhadak': ['Ishaan Khatter', 'Janhvi Kapoor', 'Ashutosh Rana', 'Ankit Bisht'],
            'Stree': ['Rajkummar Rao', 'Shraddha Kapoor', 'Pankaj Tripathi', 'Aparshakti Khurana'],
            'Badhaai Ho': ['Ayushmann Khurrana', 'Neena Gupta', 'Sanya Malhotra', 'Gajraj Rao'],
            'Andhadhun': ['Ayushmann Khurrana', 'Tabu', 'Radhika Apte', 'Anil Dhawan'],
            'Raazi': ['Alia Bhatt', 'Vicky Kaushal', 'Shishir Sharma', 'Rajit Kapur'],
            'Batti Gul Meter Chalu': ['Shahid Kapoor', 'Shraddha Kapoor', 'Yami Gautam', 'Divyendu Sharma'],
            'Gold': ['Akshay Kumar', 'Mouni Roy', 'Kunal Kapoor', 'Amit Sadh'],
            'Satyam Shivam Sundaram': ['Rani Mukerji', 'Sushant Singh Rajput'],
            'Sonu Ke Titu Ki Sweety': ['Kartik Aaryan', 'Nushrat Bharucha', 'Sunny Singh', 'Alok Nath'],
            'Veere Di Wedding': ['Sonam Kapoor', 'Swara Bhasker', 'Shikha Talsania', 'Kareena Kapoor Khan'],
            'Baaghi 2': ['Tiger Shroff', 'Disha Patani', 'Randeep Hooda', 'Prateik Babbar'],
            'Padmaavat': ['Deepika Padukone', 'Ranveer Singh', 'Shahid Kapoor', 'Aditi Rao Hydari'],
            'Race 3': ['Salman Khan', 'Jacqueline Fernandez', 'Bobby Deol', 'Anil Kapoor'],
            'Thugs of Hindostan': ['Amitabh Bachchan', 'Aamir Khan', 'Katrina Kaif', 'Fatima Sana Shaikh'],
            'Kedarnath': ['Sushant Singh Rajput', 'Sara Ali Khan', 'Nashruddin Shah', 'Alka Kaushal'],
            'Sanju': ['Ranbir Kapoor', 'Paresh Rawal', 'Vicky Kaushal', 'Anushka Sharma'],
            'Bajirao Mastani (Re-release)': ['Ranveer Singh', 'Deepika Padukone', 'Priyanka Chopra'],
            'October': ['Varun Dhawan', 'Banita Sandhu', 'Gitanjali Rao', 'Shivendra Singh'],
            'Laila Majnu': ['Avinash Tiwary', 'Tripti Dimri', 'Sumit Kaul', 'Sushil Dahiya'],
            'Pataakha': ['Sanya Malhotra', 'Radhika Madan', 'Vijay Raaz', 'Sunil Grover'],
            'Hawaizaada': ['Ayushmann Khurrana', 'Pooja Salvi', 'Nimrat Kaur', 'Ankur Vikal'],
            'Mukkabaaz': ['Vineet Kumar Singh', 'Zoya Hussain', 'Jimmy Sheirgill', 'Ravi Kishan'],
            'FryDay': ['Govinda', 'Varun Sharma', 'Rajesh Sharma', 'Saurabh Shukla'],
            'Mitron': ['Jackky Bhagnani', 'Kritika Kamra', 'Pratik Gandhi', 'Neeraj Sood'],
            'Nanu Ki Jaanu': ['Abhay Deol', 'Patralekha', 'Manu Rishi Chadha', 'Sumit Gulati'],
            'Badla': ['Amitabh Bachchan', 'Taapsee Pannu', 'Tony Luke', 'Amrita Singh'],
            'Luka Chuppi': ['Kartik Aaryan', 'Kriti Sanon', 'Aparshakti Khurana', 'Pankaj Tripathi'],
            'Madhuri Dixit’s Film': ['Madhuri Dixit', 'Sumeet Vyas'],
            'Raat Akeli Hai': ['Nawazuddin Siddiqui', 'Radhika Apte', 'Shweta Tripathi', 'Kali Prasad Mukherjee'],
            'Dabangg 3': ['Salman Khan', 'Sonakshi Sinha', 'Sudeep', 'Mahi Gill'],
            'Kuch Kuch Hota Hai (Re-release)': ['Shah Rukh Khan', 'Kajol', 'Rani Mukerji'],

            # 2017 Movies
            'Baahubali 2: The Conclusion': ['Prabhas', 'Anushka Shetty', 'Rana Daggubati', 'Tamannaah Bhatia'],
            'Dangal': ['Aamir Khan', 'Fatima Sana Shaikh', 'Sanya Malhotra', 'Zaira Wasim'],
            'Jab Harry Met Sejal': ['Shah Rukh Khan', 'Anushka Sharma', 'Sayani Gupta', 'Chandan Roy Sanyal'],
            'Raees': ['Shah Rukh Khan', 'Mahira Khan', 'Nawazuddin Siddiqui', 'Jagannath Nivangune'],
            'Tubelight': ['Salman Khan', 'Sohail Khan', 'Matin Rey Tangu', 'Zhu Zhu'],
            'Badrinath Ki Dulhania': ['Varun Dhawan', 'Alia Bhatt', 'Sahil Vaid', 'Aparshakti Khurana'],
            'The Ghazi Attack': ['Rana Daggubati', 'Taapsee Pannu', 'Kunal Kapoor', 'Atul Kulkarni'],
            'Judwaa 2': ['Varun Dhawan', 'Jacqueline Fernandez', 'Taapsee Pannu', 'Anupam Kher'],
            'Toilet: Ek Prem Katha': ['Akshay Kumar', 'Bhumi Pednekar', 'Anupam Kher', 'Divyendu Sharma'],
            'Goliyon Ki Raasleela Ram-Leela': ['Ranveer Singh', 'Deepika Padukone', 'Supriya Pathak', 'Richa Chadda'],
            'Dear Zindagi': ['Shah Rukh Khan', 'Alia Bhatt', 'Kunal Kapoor', 'Aditya Roy Kapur'],
            'Judwaa 2': ['Varun Dhawan', 'Jacqueline Fernandez', 'Taapsee Pannu', 'Anupam Kher'],
            'Tumhari Sulu': ['Vidya Balan', 'Manav Kaul', 'Neha Dhupia', 'Rajesh Sharma'],
            'Bareilly Ki Barfi': ['Kriti Sanon', 'Rajkummar Rao', 'Ayushmann Khurrana', 'Pankaj Tripathi'],
            'Shubh Mangal Saavdhan': ['Ayushmann Khurrana', 'Bhumi Pednekar', 'Seema Pahwa', 'Anshul Chauhan'],
            'The Lunchbox': ['Irrfan Khan', 'Nimrat Kaur', 'Nakul Vaid', 'Dalip Tahil'],
            'Badrinath Ki Dulhania': ['Varun Dhawan', 'Alia Bhatt', 'Sahil Vaid', 'Aparshakti Khurana'],
            'Raabta': ['Sushant Singh Rajput', 'Kriti Sanon', 'Rajkummar Rao', 'Vikram Singh'],
            'Tumhari Sulu': ['Vidya Balan', 'Manav Kaul', 'Neha Dhupia', 'Rajesh Sharma'],
            'Judwaa 2': ['Varun Dhawan', 'Jacqueline Fernandez', 'Taapsee Pannu', 'Anupam Kher'],
            'Baadshaho': ['Ajay Devgn', 'Emraan Hashmi', 'Ileana D’Cruz', 'Esha Gupta'],
            'Chef': ['Saif Ali Khan', 'Padmapriya Janakiraman', 'Saurabh Shukla', 'Chandan Roy Sanyal'],
            'Haseena Parkar': ['Shraddha Kapoor', 'Siddhant Kapoor', 'Ankur Bhatia', 'Rajesh Sharma'],
            'Meri Pyaari Bindu': ['Ayushmann Khurrana', 'Parineeti Chopra', 'Amitabh Bhattacharya', 'Kishore Kumar'],
            'Mom': ['Sridevi', 'Nawazuddin Siddiqui', 'Adnan Siddiqui', 'Rishi Kapoor'],
            'Bareilly Ki Barfi': ['Kriti Sanon', 'Rajkummar Rao', 'Ayushmann Khurrana', 'Pankaj Tripathi'],
            'Toilet: Ek Prem Katha': ['Akshay Kumar', 'Bhumi Pednekar', 'Anupam Kher', 'Divyendu Sharma'],
            'Mubarakan': ['Anil Kapoor', 'Arjun Kapoor', 'Ileana D’Cruz', 'Athiya Shetty'],
            'Simran': ['Kangana Ranaut', 'Sohum Shah', 'Rajat Barmecha', 'Freddy Daruwala'],
            'Laila Majnu': ['Avinash Tiwary', 'Tripti Dimri', 'Sumit Kaul', 'Sushil Dahiya'],
            'Tumhari Sulu': ['Vidya Balan', 'Manav Kaul', 'Neha Dhupia', 'Rajesh Sharma'],
            'Phullu': ['Sharib Hashmi', 'Lubna Salim', 'Naila', 'Javed Khan'],
            'The Ghazi Attack': ['Rana Daggubati', 'Taapsee Pannu', 'Kunal Kapoor', 'Atul Kulkarni'],

            # 2016 Movies
            'Dangal': ['Aamir Khan', 'Fatima Sana Shaikh', 'Sanya Malhotra', 'Zaira Wasim'],
            'Sultan': ['Salman Khan', 'Anushka Sharma', 'Randeep Hooda', 'Amit Sadh'],
            'Ae Dil Hai Mushkil': ['Ranbir Kapoor', 'Anushka Sharma', 'Aishwarya Rai Bachchan', 'Fawad Khan'],
            'Kabali': ['Rajinikanth', 'Radhika Apte', 'Winston Chao', 'Dinesh Ravi'],
            'Raman Raghav 2.0': ['Nawazuddin Siddiqui', 'Vicky Kaushal', 'Sobhita Dhulipala', 'Shriya Choudhury'],
            'Bar Bar Dekho': ['Sidharth Malhotra', 'Katrina Kaif', 'Ram Kapoor', 'Sayani Gupta'],
            'Shivaay': ['Ajay Devgn', 'Sayesha Saigal', 'Erica Kaar', 'Vir Das'],
            'Housefull 3': ['Akshay Kumar', 'Abhishek Bachchan', 'Riteish Deshmukh', 'Jacqueline Fernandez'],
            'Mohenjo Daro': ['Hrithik Roshan', 'Pooja Hegde', 'Kabir Bedi', 'Manish Choudhary'],
            'Rock On 2': ['Farhan Akhtar', 'Arjun Rampal', 'Shraddha Kapoor', 'Prachi Desai'],
            'Raees': ['Shah Rukh Khan', 'Mahira Khan', 'Nawazuddin Siddiqui', 'Zarina Wahab'],
            'Neerja': ['Sonam Kapoor', 'Shabana Azmi', 'Jim Sarbh', 'Shekhar Ravjiani'],
            'Kapoor & Sons': ['Sidharth Malhotra', 'Alia Bhatt', 'Fawad Khan', 'Rajat Kapoor'],
            'Pink': ['Amitabh Bachchan', 'Taapsee Pannu', 'Piyush Mishra', 'Andrea Tariang'],
            'Dear Zindagi': ['Shah Rukh Khan', 'Alia Bhatt', 'Kunal Kapoor', 'Aditya Roy Kapur'],
            'Ae Dil Hai Mushkil': ['Ranbir Kapoor', 'Anushka Sharma', 'Aishwarya Rai Bachchan', 'Fawad Khan'],
            'Ki & Ka': ['Arjun Kapoor', 'Kareena Kapoor Khan', 'Swaroop Sampat', 'Rajit Kapoor'],
            'Kahaani 2: Durga Rani Singh': ['Vidya Balan', 'Arjun Rampal', 'Jugal Hansraj', 'Kharaj Mukherjee'],
            'Dear Zindagi': ['Shah Rukh Khan', 'Alia Bhatt', 'Kunal Kapoor', 'Aditya Roy Kapur'],
            'Mirzya': ['Harshvardhan Kapoor', 'Saiyami Kher', 'Anuj Choudhry', 'K.K. Raina'],
            'Wazir': ['Amitabh Bachchan', 'Farhan Akhtar', 'Aditi Rao Hydari', 'Neil Nitin Mukesh'],
            'Bajirao Mastani': ['Ranveer Singh', 'Deepika Padukone', 'Priyanka Chopra', 'Tanvi Azmi'],
            'Force 2': ['John Abraham', 'Sonakshi Sinha', 'Tahir Raj Bhasin', 'Freddy Daruwala'],
            'Phantom': ['Saif Ali Khan', 'Katrina Kaif', 'Sabyasachi Chakrabarty', 'Javed Jaffrey'],
            'Baaghi': ['Tiger Shroff', 'Shraddha Kapoor', 'Sudheer Babu', 'Chunkey Pandey'],
            'Sarbjit': ['Randeep Hooda', 'Aishwarya Rai Bachchan', 'Richa Chadha', 'Darshan Kumaar'],
            'Baar Baar Dekho': ['Sidharth Malhotra', 'Katrina Kaif', 'Ram Kapoor', 'Sayani Gupta'],
            'Udta Punjab': ['Shahid Kapoor', 'Alia Bhatt', 'Kareena Kapoor Khan', 'Diljit Dosanjh'],
            'Fitoor': ['Aditya Roy Kapur', 'Katrina Kaif', 'Tabu', 'Rahul Bhat'],
            'Lajwanti': ['Rituparna Sengupta', 'Ravi Kishan', 'Sushil Singh', 'Sushil Yadav'],
            'Raaz Reboot': ['Emraan Hashmi', 'Kriti Kharbanda', 'Gaurav Arora', 'Anupam Kher'],
            'Kahaani 2: Durga Rani Singh': ['Vidya Balan', 'Arjun Rampal', 'Jugal Hansraj', 'Kharaj Mukherjee'],
            'Befikre': ['Ranveer Singh', 'Vaani Kapoor', 'Karan Wahi', 'Aditi Rao Hydari'],
            'Chup Chup Ke': ['Shahid Kapoor', 'Rani Mukerji', 'Neha Dhupia', 'Sunil Shetty'],

            # 2015 Movies
            'Bajirao Mastani': ['Ranveer Singh', 'Deepika Padukone', 'Priyanka Chopra', 'Tanvi Azmi'],
            'Dilwale': ['Shah Rukh Khan', 'Kajol', 'Varun Dhawan', 'Kriti Sanon'],
            'Tanu Weds Manu Returns': ['Kangana Ranaut', 'R. Madhavan', 'Jimmy Sheirgill', 'Deepak Dobriyal'],
            'Baaghi': ['Tiger Shroff', 'Shraddha Kapoor', 'Sudheer Babu', 'Chunkey Pandey'],
            'Piku': ['Amitabh Bachchan', 'Deepika Padukone', 'Irrfan Khan', 'Jisshu Sengupta'],
            'Prem Ratan Dhan Payo': ['Salman Khan', 'Sonam Kapoor', 'Neil Nitin Mukesh', 'Anupam Kher'],
            'Tamasha': ['Ranbir Kapoor', 'Deepika Padukone', 'Javed Sheikh', 'Piyush Mishra'],
            'Bajrangi Bhaijaan': ['Salman Khan', 'Kareena Kapoor Khan', 'Nawazuddin Siddiqui', 'Harshaali Malhotra'],
            'Brothers': ['Akshay Kumar', 'Sidharth Malhotra', 'Jacqueline Fernandez', 'Jackie Shroff'],
            'Manjhi – The Mountain Man': ['Nawazuddin Siddiqui', 'Radhika Apte', 'Tigmanshu Dhulia', 'Darshan Jariwala'],
            'Baahubali: The Beginning': ['Prabhas', 'Anushka Shetty', 'Rana Daggubati', 'Tamannaah Bhatia'],
            'Badlapur': ['Varun Dhawan', 'Yami Gautam', 'Nawazuddin Siddiqui', 'Radhika Apte'],
            'Bajirao Mastani': ['Ranveer Singh', 'Deepika Padukone', 'Priyanka Chopra', 'Tanvi Azmi'],
            'Hero': ['Sooraj Pancholi', 'Athiya Shetty', 'Aditya Pancholi', 'Tigmanshu Dhulia'],
            'Katti Batti': ['Imran Khan', 'Kangana Ranaut', 'Payal Rohatgi', 'Kumud Mishra'],
            'Phantom': ['Saif Ali Khan', 'Katrina Kaif', 'Sabyasachi Chakrabarty', 'Javed Jaffrey'],
            'Detective Byomkesh Bakshi!': ['Sushant Singh Rajput', 'Anand Tiwari', 'Meiyang Chang', 'Swastika Mukherjee'],
            'Masaan': ['Richa Chadha', 'Vicky Kaushal', 'Shweta Tripathi', 'Sanjay Mishra'],
            'Shaandaar': ['Shahid Kapoor', 'Alia Bhatt', 'Pankaj Kapur', 'Sanah Kapoor'],
            'Ki and Ka': ['Arjun Kapoor', 'Kareena Kapoor Khan', 'Swaroop Sampat', 'Rajit Kapoor'],
            'Badmashiyaan': ['Sidhant Gupta', 'Karan Mehra', 'Sharib Hashmi', 'Sonal Chauhan'],
            'Manjhi – The Mountain Man': ['Nawazuddin Siddiqui', 'Radhika Apte', 'Tigmanshu Dhulia', 'Darshan Jariwala'],
            'Shamitabh': ['Amitabh Bachchan', 'Dhanush', 'Kamalinee Mukherjee', 'Suman Talwar'],
            'Rock On 2': ['Farhan Akhtar', 'Arjun Rampal', 'Shraddha Kapoor', 'Prachi Desai'],
            'Fitoor': ['Aditya Roy Kapur', 'Katrina Kaif', 'Tabu', 'Rahul Bhat'],
            'Tamasha': ['Ranbir Kapoor', 'Deepika Padukone', 'Javed Sheikh', 'Piyush Mishra'],
            'Tanu Weds Manu Returns': ['Kangana Ranaut', 'R. Madhavan', 'Jimmy Sheirgill', 'Deepak Dobriyal'],
            'Bajirao Mastani': ['Ranveer Singh', 'Deepika Padukone', 'Priyanka Chopra', 'Tanvi Azmi'],
            'Prem Ratan Dhan Payo': ['Salman Khan', 'Sonam Kapoor', 'Neil Nitin Mukesh', 'Anupam Kher'],
            'Dilwale': ['Shah Rukh Khan', 'Kajol', 'Varun Dhawan', 'Kriti Sanon'],
            'Piku': ['Amitabh Bachchan', 'Deepika Padukone', 'Irrfan Khan', 'Jisshu Sengupta'],
            'Baaghi': ['Tiger Shroff', 'Shraddha Kapoor', 'Sudheer Babu', 'Chunkey Pandey']
        }

        self.web_series_bollywood = {
            # 2018
            'Sacred Games': ['Saif Ali Khan', 'Nawazuddin Siddiqui', 'Radhika Apte', 'Pankaj Tripathi', 'Surveen Chawla'],
            'Mirzapur': ['Pankaj Tripathi', 'Ali Fazal', 'Shweta Tripathi Sharma', 'Divyendu Sharma', 'Vikrant Massey', 'Rasika Dugal'],
            'Breathe': ['R. Madhavan', 'Amit Sadh', 'Sadhvani Singh', 'Sapna Pabbi'],
            'The Great Indian Dysfunctional Family': ['Barun Sobti', 'Shivani Tanksale', 'Rohit Chandel', 'Elli Avram'],
            
            # 2019
            'Made in Heaven': ['Sobhita Dhulipala', 'Arjun Mathur', 'Shashank Arora', 'Kalki Koechlin', 'Jim Sarbh'],
            'The Family Man': ['Manoj Bajpayee', 'Sharib Hashmi', 'Priyamani', 'Shreya Dhanwanthary', 'Sharib Hashmi'],
            'Mirzapur Season 2': ['Pankaj Tripathi', 'Ali Fazal', 'Divyendu Sharma', 'Vikrant Massey', 'Shweta Tripathi Sharma', 'Rasika Dugal'],
            'Delhi Crime': ['Shefali Shah', 'Rajesh Tailang', 'Rasika Dugal', 'Adil Hussain', 'Sandeep Shikhar'],
            'Bard of Blood': ['Emraan Hashmi', 'Sobhita Dhulipala', 'Vineet Kumar Singh', 'Jaideep Ahlawat'],
            'Panchayat': ['Jitendra Kumar', 'Raghubir Yadav', 'Neena Gupta', 'Fahad Mustafa', 'Chandan Roy'],
            
            # 2020
            'Special Ops': ['Kay Kay Menon', 'Vishal Jethwa', 'Karan Tacker', 'Saiyami Kher', 'Vinay Pathak'],
            'Scam 1992': ['Pratik Gandhi', 'Shreya Dhanwanthary', 'Hemant Kher', 'Nikhil Dwivedi', 'Raghubir Yadav'],
            'Aarya': ['Sushmita Sen', 'Chandrachur Singh', 'Ankur Bhatia', 'Nikitin Dheer'],
            'Panchayat': ['Jitendra Kumar', 'Raghubir Yadav', 'Neena Gupta', 'Fahad Mustafa', 'Chandan Roy'],
            'The Last Hour': ['Shivani Raghuvanshi', 'Shahnawaz Pradhan', 'Raghubir Yadav', 'Karma Takapa'],
            'Breathe: Into the Shadows': ['Abhishek Bachchan', 'Amit Sadh', 'Nithya Menen', 'Saiyami Kher'],
            'Criminal Justice': ['Vikrant Massey', 'Pankaj Tripathi', 'Anupriya Goenka', 'Mita Vashisht'],
            
            # 2021
            'The Family Man Season 2': ['Manoj Bajpayee', 'Sharib Hashmi', 'Priyamani', 'Shreya Dhanwanthary', 'Sharib Hashmi'],
            'The Empire': ['Kunal Kapoor', 'Shabana Azmi', 'Drashti Dhami', 'Dino Morea'],
            'Mumbai Mafia: Police vs The Underworld': ['Documentary'],
            'Tabbar': ['Pavan Malhotra', 'Sujata Kumar', 'Gagan Arora', 'Raghubir Yadav'],
            'Rocket Boys': ['Jim Sarbh', 'Ishwak Singh', 'Suhail Nayyar', 'Rajit Kapur'],
            'Tandav': ['Saif Ali Khan', 'Dimple Kapadia', 'Kareena Kapoor Khan', 'Sunil Grover'],
            'Aarya Season 2': ['Sushmita Sen', 'Chandrachur Singh', 'Ankur Bhatia', 'Nikitin Dheer', 'Vikas Kumar'],
            
            # 2022
            'The Kashmir Files (Web Version)': ['Anupam Kher', 'Mithun Chakraborty', 'Darshan Kumar', 'Pallavi Joshi'],
            'Mismatched Season 2': ['Prajakta Koli', 'Rohit Saraf', 'Rannvijay Singha', 'Vidya Malvade'],
            'Scooter': ['Rajkummar Rao', 'Sanya Malhotra', 'Vikram Singh', 'Shubham Jha'],
            'Delhi Crime Season 2': ['Shefali Shah', 'Rajesh Tailang', 'Rasika Dugal', 'Adil Hussain', 'Sandeep Shikhar'],
            'Escaype Live': ['Javed Jaffrey', 'Siddharth', 'Shweta Tripathi Sharma', 'Rohit Saraf'],
            'Class of 2009': ['Pratik Babbar', 'Nikita Dutta', 'Sanjay Kapoor', 'Anupriya Goenka', 'Madhurima Tuli'],
            'Taj: Divided by Blood': ['Naseeruddin Shah', 'Rahul Bose', 'Dharmendra', 'Aditi Rao Hydari'],
            
            # 2023
            'Farzi': ['Shahid Kapoor', 'Vijay Sethupathi', 'Raashii Khanna', 'Kay Kay Menon', 'Zeeshan Ayyub'],
            'The Night Manager (Indian Remake)': ['Aditya Roy Kapur', 'Sobhita Dhulipala', 'Anil Kapoor', 'Tillotama Shome'],
            'Taj: Divided by Blood': ['Naseeruddin Shah', 'Rahul Bose', 'Dharmendra', 'Aditi Rao Hydari'],
            'Guns & Gulaabs': ['Rajkummar Rao', 'Dulquer Salmaan', 'Gulshan Devaiah', 'Adarsh Gourav'],
            'Scam 2003: The Telgi Story': ['Shantanu Maheshwari', 'Mohan Agashe', 'Gagan Dev Riar', 'Raghubir Yadav'],
            'The Family Man Season 3': ['Manoj Bajpayee', 'Sharib Hashmi', 'Priyamani', 'Shreya Dhanwanthary', 'Sharib Hashmi'],
            'Mumbai Mafia: Police vs The Underworld': ['Documentary'],
            
            # 2024
            'The Night Manager': ['Aditya Roy Kapur', 'Sobhita Dhulipala', 'Anil Kapoor', 'Tillotama Shome', 'Rajat Kapoor'],
            'Farzi Season 2': ['Shahid Kapoor', 'Vijay Sethupathi', 'Raashii Khanna', 'Kay Kay Menon', 'Zeeshan Ayyub'],
            'Mirzapur Season 4': ['Pankaj Tripathi', 'Ali Fazal', 'Divyendu Sharma', 'Vikrant Massey', 'Shweta Tripathi Sharma', 'Rasika Dugal'],
            'The Family Man Season 3': ['Manoj Bajpayee', 'Sharib Hashmi', 'Priyamani', 'Shreya Dhanwanthary', 'Sharib Hashmi'],
            'Panchayat Season 3': ['Jitendra Kumar', 'Raghubir Yadav', 'Neena Gupta', 'Fahad Mustafa', 'Chandan Roy'],
            'Scam 2003: The Telgi Story': ['Shantanu Maheshwari', 'Mohan Agashe', 'Gagan Dev Riar', 'Raghubir Yadav'],
            'Taaza Khabar': ['Bhuvan Bam', 'Shivani Raghuvanshi', 'Deven Bhojani', 'Vijay Raaz', 'Zakir Hussain'],
            'The Great Indian Murder Season 2': ['Richa Chadha', 'Ashutosh Rana', 'Jatin Goswami', 'Vineet Kumar Singh', 'Raghubir Yadav'],
            'Made in Heaven Season 2': ['Sobhita Dhulipala', 'Arjun Mathur', 'Shashank Arora', 'Kalki Koechlin', 'Jim Sarbh'],
            'Delhi Crime Season 3': ['Shefali Shah', 'Rajesh Tailang', 'Rasika Dugal', 'Adil Hussain', 'Sandeep Shikhar'],
            'The Trial (Indian Remake of The Good Wife)': ['Kareena Kapoor Khan', 'Kubbra Sait', 'Shahnawaz Pradhan', 'Mackenzie Davis', 'Suchitra Pillai'],
            'Class of 2009': ['Pratik Babbar', 'Nikita Dutta', 'Sanjay Kapoor', 'Anupriya Goenka', 'Madhurima Tuli']
        }

        self.movies_Hollywood = {
            # 2018
            'Avengers: Infinity War': ['Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo', 'Scarlett Johansson', 'Chris Evans'],
            'Black Panther': ['Chadwick Boseman', 'Michael B. Jordan', 'Lupita Nyong\'o', 'Danai Gurira', 'Martin Freeman'],
            'Bohemian Rhapsody': ['Rami Malek', 'Lucy Boynton', 'Ben Hardy', 'Joseph Mazzello', 'Gwilym Lee'],
            'A Star Is Born': ['Lady Gaga', 'Bradley Cooper', 'Sam Elliott', 'Dave Chappelle', 'Andrew Dice Clay'],
            'Mission: Impossible – Fallout': ['Tom Cruise', 'Henry Cavill', 'Simon Pegg', 'Rebecca Ferguson', 'Ving Rhames'],
            'Incredibles 2': ['Craig T. Nelson', 'Holly Hunter', 'Sarah Vowell', 'Samuel L. Jackson', 'Brad Bird'],
            'Venom': ['Tom Hardy', 'Michelle Williams', 'Riz Ahmed', 'Woody Harrelson', 'Jenny Slate'],
            'Spider-Man: Into the Spider-Verse': ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld', 'Mahershala Ali', 'Liev Schreiber'],
            'Deadpool 2': ['Ryan Reynolds', 'Josh Brolin', 'Zazie Beetz', 'T.J. Miller', 'Morena Baccarin'],
            'Jurassic World: Fallen Kingdom': ['Chris Pratt', 'Bryce Dallas Howard', 'Rafe Spall', 'Toby Jones', 'Justice Smith'],

            # 2019
            'Avengers: Endgame': ['Robert Downey Jr.', 'Chris Hemsworth', 'Scarlett Johansson', 'Mark Ruffalo', 'Chris Evans'],
            'Joker': ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz', 'Frances Conroy', 'Brett Cullen'],
            'Once Upon a Time in Hollywood': ['Leonardo DiCaprio', 'Brad Pitt', 'Margot Robbie', 'Al Pacino', 'Kurt Russell'],
            'The Lion King': ['Donald Glover', 'Beyoncé', 'Seth Rogen', 'Chiwetel Ejiofor', 'Billy Eichner'],
            'Toy Story 4': ['Tom Hanks', 'Tim Allen', 'Annie Potts', 'Tony Hale', 'Keegan-Michael Key'],
            'Parasite': ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik', 'Park So-dam'],
            'It Chapter Two': ['James McAvoy', 'Jessica Chastain', 'Bill Hader', 'Isaiah Mustafa', 'Jay Ryan'],
            'John Wick: Chapter 3 – Parabellum': ['Keanu Reeves', 'Halle Berry', 'Ian McShane', 'Laurence Fishburne', 'Ruby Rose'],
            'Frozen II': ['Idina Menzel', 'Kristen Bell', 'Josh Gad', 'Evan Rachel Wood', 'Sterling K. Brown'],
            'Shazam!': ['Zachary Levi', 'Asher Angel', 'Jack Dylan Grazer', 'Mark Strong', 'Marta Milans'],

            # 2020
            'Tenet': ['John David Washington', 'Robert Pattinson', 'Elizabeth Debicki', 'Dimple Kapadia', 'Kenneth Branagh'],
            'Birds of Prey': ['Margot Robbie', 'Rosie Perez', 'Mary Elizabeth Winstead', 'Jurnee Smollett', 'Ewan McGregor'],
            'Wonder Woman 1984': ['Gal Gadot', 'Chris Pine', 'Kristen Wiig', 'Pedro Pascal', 'Robin Wright'],
            'Soul': ['Jamie Foxx', 'Tina Fey', 'Phylicia Rashad', 'Angela Bassett', 'Questlove'],
            'Mulan': ['Liu Yifei', 'Donnie Yen', 'Jason Scott Lee', 'Yoson An', 'Gong Li'],
            'The Invisible Man': ['Elisabeth Moss', 'Oliver Jackson-Cohen', 'Harriet Dyer', 'Aldis Hodge', 'Michael Dorman'],
            'The Trial of the Chicago 7': ['Eddie Redmayne', 'Sacha Baron Cohen', 'Mark Rylance', 'Joseph Gordon-Levitt', 'Jeremy Strong'],
            'The Way Back': ['Ben Affleck', 'Al Madrigal', 'Janina Gavankar', 'Glynn Turman', 'Michaela Watkins'],
            'Wonder Woman 1984': ['Gal Gadot', 'Chris Pine', 'Kristen Wiig', 'Pedro Pascal', 'Robin Wright'],
            'The Gentlemen': ['Matthew McConaughey', 'Charlie Hunnam', 'Michelle Dockery', 'Henry Golding', 'Hugh Grant'],

            # 2021
            'Spider-Man: No Way Home': ['Tom Holland', 'Zendaya', 'Benedict Cumberbatch', 'Jacob Batalon', 'Marisa Tomei'],
            'Dune': ['Timothée Chalamet', 'Zendaya', 'Oscar Isaac', 'Rebecca Ferguson', 'Jason Momoa'],
            'No Time to Die': ['Daniel Craig', 'Rami Malek', 'Ana de Armas', 'Ralph Fiennes', 'Naomie Harris'],
            'A Quiet Place Part II': ['Emily Blunt', 'Cillian Murphy', 'Millicent Simmonds', 'Noah Jupe', 'John Krasinski'],
            'Black Widow': ['Scarlett Johansson', 'Florence Pugh', 'David Harbour', 'Rachel Weisz', 'O-T Fagbenle'],
            'The Suicide Squad': ['Margot Robbie', 'Idris Elba', 'John Cena', 'Sylvester Stallone', 'Viola Davis'],
            'Eternals': ['Gemma Chan', 'Richard Madden', 'Angelina Jolie', 'Salma Hayek', 'Kit Harington'],
            'Jungle Cruise': ['Dwayne Johnson', 'Emily Blunt', 'Jack Whitehall', 'Paul Giamatti', 'Édgar Ramírez'],
            'Matrix Resurrections': ['Keanu Reeves', 'Carrie-Anne Moss', 'Yahya Abdul-Mateen II', 'Jessica Henwick', 'Jonathan Groff'],
            'The French Dispatch': ['Timothée Chalamet', 'Frances McDormand', 'Bill Murray', 'Benicio del Toro', 'Tilda Swinton'],

            # 2022
            'Avatar: The Way of Water': ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Kate Winslet', 'Stephen Lang'],
            'Doctor Strange in the Multiverse of Madness': ['Benedict Cumberbatch', 'Elizabeth Olsen', 'Benedict Wong', 'Xochitl Gomez', 'Chiwetel Ejiofor'],
            'Thor: Love and Thunder': ['Chris Hemsworth', 'Natalie Portman', 'Christian Bale', 'Tessa Thompson', 'Taika Waititi'],
            'Jurassic World: Dominion': ['Chris Pratt', 'Bryce Dallas Howard', 'Laura Dern', 'Jeff Goldblum', 'Sam Neill'],
            'The Batman': ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano', 'Colin Farrell', 'Jeffrey Wright'],
            'Black Panther: Wakanda Forever': ['Letitia Wright', 'Angela Bassett', 'Lupita Nyong\'o', 'Danai Gurira', 'Martin Freeman'],
            'Avatar 2': ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang', 'Kate Winslet'],
            'Scream': ['Neve Campbell', 'Courteney Cox', 'David Arquette', 'Jenna Ortega', 'Jack Quaid'],
            'Nope': ['Daniel Kaluuya', 'Keke Palmer', 'Steven Yeun', 'Brandon Perea', 'Michael Wincott'],
            'Everything Everywhere All at Once': ['Michelle Yeoh', 'Stephanie Hsu', 'Ke Huy Quan', 'Jamie Lee Curtis', 'James Hong'],

            # 2023
            'Guardians of the Galaxy Vol. 3': ['Chris Pratt', 'Zoe Saldana', 'Dave Bautista', 'Karen Gillan', 'Vin Diesel'],
            'Mission: Impossible – Dead Reckoning Part One': ['Tom Cruise', 'Hayley Atwell', 'Simon Pegg', 'Rebecca Ferguson', 'Ving Rhames'],
            'Barbie': ['Margot Robbie', 'Ryan Gosling', 'Simu Liu', 'Will Ferrell', 'Issa Rae'],
            'Oppenheimer': ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.', 'Matt Damon', 'Florence Pugh'],
            'The Flash': ['Ezra Miller', 'Michael Keaton', 'Ben Affleck', 'Sasha Calle', 'Michael Shannon'],
            'Indiana Jones and the Dial of Destiny': ['Harrison Ford', 'Phoebe Waller-Bridge', 'Mads Mikkelsen', 'Antonio Banderas', 'John Rhys-Davies'],
            'John Wick: Chapter 4': ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård', 'Hiroyuki Sanada', 'Lance Reddick'],
            'Creed III': ['Michael B. Jordan', 'Jonathan Majors', 'Tessa Thompson', 'Wood Harris', 'Phylicia Rashad'],
            'The Marvels': ['Brie Larson', 'Iman Vellani', 'Teyonah Parris', 'Zawe Ashton', 'Park Seo-jun'],
            'Transformers: Rise of the Beasts': ['Anthony Ramos', 'Dominique Fishback', 'Ron Perlman', 'Peter Cullen', 'Michelle Yeoh'],

            # 2024
            'Deadpool 3': ['Ryan Reynolds', 'Hugh Jackman', 'Blake Lively', 'Morena Baccarin', 'Vanessa Hudgens'],
            'Mission: Impossible – Dead Reckoning Part Two': ['Tom Cruise', 'Hayley Atwell', 'Simon Pegg', 'Rebecca Ferguson', 'Ving Rhames'],
            'Dune: Part Two': ['Timothée Chalamet', 'Zendaya', 'Oscar Isaac', 'Rebecca Ferguson', 'Jason Momoa'],
            'Avengers: The Kang Dynasty': ['Robert Downey Jr.', 'Chris Hemsworth', 'Scarlett Johansson', 'Benedict Cumberbatch', 'Tom Holland'],
            'The Hunger Games: The Ballad of Songbirds and Snakes': ['Rachel Zegler', 'Tom Blyth', 'Hunter Schafer', 'Peter Dinklage', 'Jason Schwartzman'],
            'Fantastic Four (Reboot)': ['Unknown Cast', 'Unknown Cast', 'Unknown Cast', 'Unknown Cast'],
            'Captain America: New World Order': ['Anthony Mackie', 'Sebastian Stan', 'Harrison Ford', 'Shira Haas', 'Danny Ramirez'],
            'The Flash 2': ['Ezra Miller', 'Michael Keaton', 'Ben Affleck', 'Sasha Calle', 'Michael Shannon']
        }

        self.web_series_hollywood = {
            # 2018
            'The Haunting of Hill House': ['Michiel Huisman', 'Elisabeth Reaser', 'Oliver Jackson-Cohen', 'Victoria Pedretti', 'Carla Gugino'],
            'Narcos: Mexico': ['Diego Luna', 'Michael Peňa', 'Scoot McNairy', 'José María Yazpik', 'Fernanda Urrejola'],
            'Bodyguard': ['Richard Madden', 'Keeley Hawes', 'Ginny Holder', 'Stephanie Hyam', 'Diana Kent'],
            'The Punisher': ['Jon Bernthal', 'Ebon Moss-Bachrach', 'Deborah Ann Woll', 'Ben Barnes', 'Paul Schulze'],
            'You': ['Penn Badgley', 'Elizabeth Lail', 'Shay Mitchell', 'Zach Cherry', 'John Stamos'],
            'Altered Carbon': ['Joel Kinnaman', 'Martha Higareda', 'James Purefoy', 'Ato Essandoh', 'Chris Conner'],
            
            # 2019
            'The Witcher': ['Henry Cavill', 'Anya Chalotra', 'Freya Allan', 'Joey Batey', 'MyAnna Buring'],
            'Chernobyl': ['Jared Harris', 'Stellan Skarsgård', 'Emily Watson', 'Paul Ritter', 'Adam Nagaitis'],
            'The Mandalorian': ['Pedro Pascal', 'Gina Carano', 'Carl Weathers', 'Werner Herzog', 'Giancarlo Esposito'],
            'Watchmen': ['Regina King', 'Don Johnson', 'Tim Blake Nelson', 'Louis Gossett Jr.', 'Jeremy Irons'],
            'The Umbrella Academy': ['Elliot Page', 'Tom Hopper', 'David Castañeda', 'Robert Sheehan', 'Aidan Gallagher'],
            'Stranger Things 3': ['Winona Ryder', 'David Harbour', 'Millie Bobby Brown', 'Finn Wolfhard', 'Gaten Matarazzo'],
            'The Boys': ['Karl Urban', 'Jack Quaid', 'Erin Moriarty', 'Antony Starr', 'Chace Crawford'],
            'Fleabag': ['Phoebe Waller-Bridge', 'Sian Clifford', 'Olivia Colman', 'Bill Paterson', 'Andrew Scott'],
            'When They See Us': ['Aunjanue Ellis', 'Michael K. Williams', 'John Leguizamo', 'Caleel Harris', 'Jharrel Jerome'],
            
            # 2020
            'The Queen\'s Gambit': ['Anya Taylor-Joy', 'Bill Camp', 'Marielle Heller', 'Thomas Brodie-Sangster', 'Moses Ingram'],
            'The Mandalorian Season 2': ['Pedro Pascal', 'Gina Carano', 'Carl Weathers', 'Giancarlo Esposito', 'Temuera Morrison'],
            'The Boys Season 2': ['Karl Urban', 'Jack Quaid', 'Erin Moriarty', 'Antony Starr', 'Chace Crawford'],
            'Reacher': ['Alan Ritchson', 'Malcolm Goodwin', 'Willa Fitzgerald', 'Chris Webster', 'Maria Sten'],
            'Fargo (Season 4)': ['Chris Rock', 'Jason Schwartzman', 'Ben Whishaw', 'Jesse Buckley', 'Salvatore Esposito'],
            'The Outsider': ['Ben Mendelsohn', 'Cynthia Erivo', 'Bill Camp', 'Jason Bateman', 'Julianne Nicholson'],
            'Love Craft Country': ['Jonathan Majors', 'Jurnee Smollett', 'Courtney B. Vance', 'Michael K. Williams', 'Aunjanue Ellis'],
            'Ted Lasso': ['Jason Sudeikis', 'Hannah Waddingham', 'Brett Goldstein', 'Brendan Hunt', 'Jeremy Swift'],
            'The Trial of Chicago 7': ['Eddie Redmayne', 'Sacha Baron Cohen', 'Mark Rylance', 'Joseph Gordon-Levitt', 'Jeremy Strong'],
            
            # 2021
            'Squid Game': ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon', 'Jung Ho-yeon', 'O Yeong-su'],
            'Loki': ['Tom Hiddleston', 'Owen Wilson', 'Sophia Di Martino', 'Gugu Mbatha-Raw', 'Wunmi Mosaku'],
            'Money Heist (Season 5)': ['Álvaro Morte', 'Úrsula Corberó', 'Itziar Ituño', 'Pedro Alonso', 'Miguel Herrán'],
            'Reacher (Season 1)': ['Alan Ritchson', 'Malcolm Goodwin', 'Willa Fitzgerald', 'Chris Webster', 'Maria Sten'],
            'The Witcher Season 2': ['Henry Cavill', 'Anya Chalotra', 'Freya Allan', 'Joey Batey', 'MyAnna Buring'],
            'Stranger Things 4': ['Winona Ryder', 'David Harbour', 'Millie Bobby Brown', 'Finn Wolfhard', 'Gaten Matarazzo'],
            'Hawkeye': ['Jeremy Renner', 'Hailee Steinfeld', 'Florence Pugh', 'Vera Farmiga', 'Tony Dalton'],
            'The Falcon and the Winter Soldier': ['Anthony Mackie', 'Sebastian Stan', 'Wyatt Russell', 'Daniel Brühl', 'Emily VanCamp'],
            'Mare of Easttown': ['Kate Winslet', 'Evan Peters', 'Julianne Nicholson', 'Jean Smart', 'Angourie Rice'],
            'WandaVision': ['Elizabeth Olsen', 'Paul Bettany', 'Kathryn Hahn', 'Teyonah Parris', 'Randall Park'],
            
            # 2022
            'Stranger Things 4': ['Winona Ryder', 'David Harbour', 'Millie Bobby Brown', 'Finn Wolfhard', 'Gaten Matarazzo'],
            'The Bear': ['Jeremy Allen White', 'Ebon Moss-Bachrach', 'Ayo Edebiri', 'Liza Colón-Zayas', 'Abby Elliott'],
            'House of the Dragon': ['Paddy Considine', 'Emma D’Arcy', 'Matt Smith', 'Olivia Cooke', 'Stefanie Martini'],
            'Reacher (Season 2)': ['Alan Ritchson', 'Malcolm Goodwin', 'Willa Fitzgerald', 'Chris Webster', 'Maria Sten'],
            'Andor': ['Diego Luna', 'Stellan Skarsgård', 'Adria Arjona', 'Fiona Shaw', 'Kyle Soller'],
            'Wednesday': ['Jenna Ortega', 'Catherine Zeta-Jones', 'Luis Guzmán', 'Riki Lindhome', 'Gwendoline Christie'],
            'The Sandman': ['Tom Sturridge', 'Gwendoline Christie', 'Vivienne Acheampong', 'Boyd Holbrook', 'Charles Dance'],
            'The White Lotus (Season 2)': ['Jennifer Coolidge', 'Aubrey Plaza', 'Theo James', 'Meghann Fahy', 'Adam DiMarco'],
            'Better Call Saul (Final Season)': ['Bob Odenkirk', 'Rhea Seehorn', 'Jonathan Banks', 'Giancarlo Esposito', 'Patrick Fabian'],
            'The Boys: Diabolical': ['Karl Urban', 'Jack Quaid', 'Erin Moriarty', 'Antony Starr', 'Chace Crawford'],
            
            # 2023
            'The Last of Us': ['Pedro Pascal', 'Bella Ramsey', 'Nico Parker', 'Murray Bartlett', 'Anna Torv'],
            'Reacher (Season 2)': ['Alan Ritchson', 'Malcolm Goodwin', 'Willa Fitzgerald', 'Chris Webster', 'Maria Sten'],
            'The Bear Season 2': ['Jeremy Allen White', 'Ebon Moss-Bachrach', 'Ayo Edebiri', 'Liza Colón-Zayas', 'Abby Elliott'],
            'Secret Invasion': ['Samuel L. Jackson', 'Ben Mendelsohn', 'Olivia Colman', 'Don Cheadle', 'Cobie Smulders'],
            'The Mandalorian Season 3': ['Pedro Pascal', 'Gina Carano', 'Carl Weathers', 'Giancarlo Esposito', 'Temuera Morrison'],
            'The Sandman Season 2': ['Tom Sturridge', 'Gwendoline Christie', 'Vivienne Acheampong', 'Boyd Holbrook', 'Charles Dance'],
            'The Boys Season 4': ['Karl Urban', 'Jack Quaid', 'Erin Moriarty', 'Antony Starr', 'Chace Crawford'],
            'Loki Season 2': ['Tom Hiddleston', 'Owen Wilson', 'Sophia Di Martino', 'Gugu Mbatha-Raw', 'Wunmi Mosaku'],
            'Jack Ryan (Season 4)': ['John Krasinski', 'Wendell Pierce', 'Abbie Cornish', 'Michael Kelly', 'Ali Suliman'],
            'The Fall of the House of Usher': ['Mark Hamill', 'Bruce Greenwood', 'Carla Gugino', 'Mary McDonnell', 'Henry Thomas'],
            
            # 2024
            'Reacher Season 3': ['Alan Ritchson', 'Malcolm Goodwin', 'Willa Fitzgerald', 'Chris Webster', 'Maria Sten'],
            'The Day of the Jackal': ['Unnamed Cast', 'Unnamed Cast', 'Unnamed Cast', 'Unnamed Cast', 'Unnamed Cast'],
            'Ahsoka': ['Rosario Dawson', 'Natasha Liu Bordizzo', 'Mary Elizabeth Winstead', 'Diana Lee Inosanto', 'David Tennant'],
            'The Mandalorian Season 4': ['Pedro Pascal', 'Gina Carano', 'Carl Weathers', 'Giancarlo Esposito', 'Temuera Morrison'],
            'Blade Runner 2099': ['Unnamed Cast', 'Unnamed Cast', 'Unnamed Cast', 'Unnamed Cast', 'Unnamed Cast'],
        }

        self.bhojpuri_movies = {
            # 2018
            'Satyam Shivam Sundaram': ['Khesari Lal Yadav', 'Priyanka Pandit', 'Rani Chatterjee', 'Amit Shukla'],
            'Bairagi': ['Khesari Lal Yadav', 'Kajal Raghwani', 'Ravi Kishan', 'Subhi Sharma'],
            'Nirahua Rickshawala 2': ['Dinesh Lal Yadav (Nirahua)', 'Amrapali Dubey', 'Sushil Singh', 'Anup Arora'],
            'Shubh Aarambh': ['Khesari Lal Yadav', 'Kajol Raghwani', 'Gaurav Jha', 'Sanjay Pandey'],
            'Sangharsh': ['Khesari Lal Yadav', 'Nirahua', 'Rani Chatterjee', 'Priyanka Pandit'],
            
            # 2019
            'Maine Dil Tujhko Diya': ['Khesari Lal Yadav', 'Priyanka Pandit', 'Anjana Singh', 'Amit Shukla'],
            'Dhadkan': ['Pawan Singh', 'Akshara Singh', 'Anjana Singh', 'Rani Chatterjee'],
            'Rakhwala': ['Pawan Singh', 'Kajal Raghwani', 'Nirahua', 'Rani Chatterjee'],
            'Gulabo Sitabo': ['Amitabh Bachchan', 'Ayushmann Khurrana', 'Farrukh Jaffar', 'Sujat Wagh'],
            'Raja Babu': ['Dinesh Lal Yadav (Nirahua)', 'Amrapali Dubey', 'Manoj Tiwari', 'Kajal Raghwani'],
            'Baazigar': ['Khesari Lal Yadav', 'Nidhi Jha', 'Priti Biswas', 'Yashika Verma'],
            
            # 2020
            'Shubh Aarambh': ['Khesari Lal Yadav', 'Kajal Raghwani', 'Gaurav Jha', 'Sanjay Pandey'],
            'Mera Vachan': ['Dinesh Lal Yadav (Nirahua)', 'Akshara Singh', 'Manoj Tiwari', 'Priyanka Pandit'],
            'Dulhan Chahi Pakistan Se': ['Pawan Singh', 'Kajal Raghwani', 'Anjana Singh', 'Khesari Lal Yadav'],
            'Didi Ke Pallu': ['Khesari Lal Yadav', 'Amrapali Dubey', 'Ravi Kishan', 'Kajal Raghwani'],
            'Babu Babu': ['Dinesh Lal Yadav (Nirahua)', 'Rani Chatterjee', 'Nidhi Jha', 'Kajal Raghwani'],
            
            # 2021
            'Gharwahi Ke Rakhwala': ['Pawan Singh', 'Akshara Singh', 'Amit Shukla', 'Anjana Singh'],
            'Pyaar Kiya To Darna Kya': ['Dinesh Lal Yadav (Nirahua)', 'Amrapali Dubey', 'Nidhi Jha', 'Rani Chatterjee'],
            'Dil Hai Ke Manta Nahin': ['Khesari Lal Yadav', 'Rani Chatterjee', 'Akshara Singh', 'Priyanka Pandit'],
            'Nirahua Hindustani 4': ['Dinesh Lal Yadav (Nirahua)', 'Amrapali Dubey', 'Shubhi Sharma', 'Manoj Tiwari'],
            'Mehndi Laga Ke Rakhna 3': ['Khesari Lal Yadav', 'Kajol Raghwani', 'Priyanka Pandit', 'Ravi Kishan'],
            
            # 2022
            'Khiladi': ['Pawan Singh', 'Kajal Raghwani', 'Anjana Singh', 'Ravi Kishan'],
            'Khesari Ke Dilwale': ['Khesari Lal Yadav', 'Amrapali Dubey', 'Ravi Kishan', 'Nidhi Jha'],
            'Dilwale': ['Dinesh Lal Yadav (Nirahua)', 'Amrapali Dubey', 'Akshara Singh', 'Ravi Kishan'],
            'Bhaiya Ke Sali': ['Khesari Lal Yadav', 'Priyanka Pandit', 'Rani Chatterjee', 'Kajal Raghwani'],
            'Pyar Ke Liye Kuch Bhi Karna': ['Pawan Singh', 'Kajal Raghwani', 'Anjana Singh', 'Manoj Tiwari'],
            
            # 2023
            'Patna Se Pakistan': ['Khesari Lal Yadav', 'Shubhi Sharma', 'Amrapali Dubey', 'Nidhi Jha'],
            'Mangal Pandey': ['Dinesh Lal Yadav (Nirahua)', 'Amrapali Dubey', 'Ravi Kishan', 'Shubhi Sharma'],
            'Jai Hind': ['Pawan Singh', 'Kajal Raghwani', 'Anjana Singh', 'Manoj Tiwari'],
            'Meri Jaan': ['Khesari Lal Yadav', 'Rani Chatterjee', 'Priyanka Pandit', 'Amit Shukla'],
            'Ziddi': ['Pawan Singh', 'Kajal Raghwani', 'Akshara Singh', 'Ravi Kishan'],
            
            # 2024
            'Duniya Ke Sabse Bada Rakhwala': ['Khesari Lal Yadav', 'Rani Chatterjee', 'Ravi Kishan', 'Anjana Singh'],
            'Dil Ke Duniya': ['Pawan Singh', 'Kajal Raghwani', 'Amrapali Dubey', 'Anjana Singh'],
            'Maa Ka Doodh': ['Khesari Lal Yadav', 'Nidhi Jha', 'Shubhi Sharma', 'Priyanka Pandit'],
            'Rakhwala 2': ['Dinesh Lal Yadav (Nirahua)', 'Amrapali Dubey', 'Ravi Kishan', 'Kajal Raghwani'],
            'Dhol Bhari': ['Pawan Singh', 'Rani Chatterjee', 'Anjana Singh', 'Kajal Raghwani'],
        }
    def find_movies_with_actors(self, actor_list):
        result = []
        
        # Check in Bollywood movies
        for movie, cast in self.movies_bollywood.items():
            if all(actor in cast for actor in actor_list):
                result.append(movie)

        # Check in Bollywood web series
        for movie, cast in self.web_series_bollywood.items():
            if all(actor in cast for actor in actor_list):
                result.append(movie)

        # Check in Hollywood movies
        for movie, cast in self.movies_Hollywood.items():
            if all(actor in cast for actor in actor_list):
                result.append(movie)

        # Check in Hollywood web series
        for movie, cast in self.web_series_hollywood.items():
            if all(actor in cast for actor in actor_list):
                result.append(movie)

        # Check in Bhojpuri movies
        for movie, cast in self.bhojpuri_movies.items():
            if all(actor in cast for actor in actor_list):
                result.append(movie)
        
        return result

